### ISSUE TITLE
GUI update suggestions

### ISSUE THREAD

**Issue by Rak1ta** [Botspot/pi-apps#1825]
1. Is it possible to put the menu item "back" additionally at the end of the list of programs? In order not to scroll back to return.
2. When you try to move the program description window or expand the window to view the text - everything disappears. Is it possible to make it so that it is removed only at the request of the user? I open the program script - I close Geany - the window with the description disappears.
3. Black popup borders / menu item (zoom PWA) is overridden

![Безымянный](https://user-images.githubusercontent.com/88277343/168654769-3b29bcb5-aa4d-49bb-a685-889abd3f5599.png)
![Безымянный2](https://user-images.githubusercontent.com/88277343/168644563-e8ca418f-b954-45a4-bd9c-e57544a8f7bf.png)
![Безымянный4](https://user-images.githubusercontent.com/88277343/168645500-87219df7-0db5-4303-8c14-bef5766253df.png)

**Comment by Crilum** [comment]
@Botspot @theofficialgman Can the columns be made a little narrower? (Or the whole window a little wider, it seems the minimum width with no scrollbar is about 260px.) I don't see any reason for the x dimension scrollbar.. And it just causes problems as seen here.

**Comment by Crilum** [comment]
@Rak1ta I don't have the black tooltip corners (as seen below), but then again, I don't have the default RPiOS PiXflat theme.
![2022-05-16-115112_1024x768_scrot](https://user-images.githubusercontent.com/91354257/168654337-7d01af68-a388-4a42-a7d2-95489c9b3b36.png)

I don't think this is a problem Pi-Apps can fix, this is probably a problem with GTK, or YAD.

**Comment by theofficialgman** [comment]
my right hand side scrollbar display ON TOP OF the list, meaning it doesn't take up any list width.
this is not the case here, it looks like the users scrollbar on the right is taking up horizontal space. the Persepolis Download Manager is "just a bit" too wide to fit in that case and the scrollbar gets added.

**Comment by Rak1ta** [comment]
> the GUI is not intended to be moved since its position can not be obtained
But the external window "Updates available" works as I described. :-(

**Comment by theofficialgman** [comment]
> > the GUI is not intended to be moved since its position can not be obtained
> 
> But the external window "Updates available" works as I described. :-(

yes, this window does not close automatically on losing focus. the new GUI would not function as intended if the window didn't close automatically, users would click on an app, then click on another app, and the previous apps details page would still be visible

**Comment by Botspot** [comment]
I've also noticed black corners on all GTK tooltips when using PiXflat theme. I think the problem comes from the compositor RPiOS uses uses, or maybe mutter. There's definitely nothing Pi-Apps can to to fix it, other than disabling tooltips.

Adding a Back button to the end of longer lists is a splendid idea.

**Comment by Crilum** [comment]
I thought about a `Back to Top` button but then realized yad probably can't do that...

**Comment by Botspot** [comment]
One possible way to avoid unwanted closure of the app details window would be to make it close only when the current selection changes. However this may cause unforeseen edge cases.

**Comment by Rak1ta** [comment]
> close only when the current selection changes

Why not leave those windows open? Let's say I put apps on raspberry for the first time. I open the windows of all programs that interest me, study the description. If required, I press "install" or use the excellent "[X]" button, which will close only what I do not need.

**Comment by Crilum** [comment]
> > I thought about a `Back to Top` button but then realized yad probably can't do that...
> 
> A special list item to trigger a list refresh would effectively do this. We will have to choose which function is more convenient for most users. I think "Back" would be more used.

Well, it just seems kind of weird to have two back buttons, so I was thinking a `Back to Top` button would help the user get back to the top without having to scroll, which mitigates the need for another `Back` button.

**Comment by Crilum** [comment]
> > close only when the current selection changes
> 
> Why not leave those windows open? Let's say I put apps on raspberry for the first time. I open the windows of all programs that interest me, study the description. If required, I press "install" or use the excellent "[X]" button, which will close only what I do not need.

Because that would end up being a lot of windows to close.. I do agree that it's kind of annoying that they just *close*, if they're not focused...

**Comment by Botspot** [comment]
Hey everyone, what do you think of enlarging the gui window if the screen dimensions allow for it?
Before:
![2022-05-19-150304_1920x1080_scrot](https://user-images.githubusercontent.com/54716352/169395112-b1ce62b2-46f4-4376-8200-95f12e7baaa4.png)
After:
![2022-05-19-150211_1920x1080_scrot](https://user-images.githubusercontent.com/54716352/169394986-448c0301-d502-45c2-8db0-88f0ae00b235.png)

**Comment by Jai-JAP** [comment]
Looks good

**Comment by Botspot** [comment]
> Looks good

Done.

**Comment by Rak1ta** [comment]
@Botspot A large image "breaks" the description of the program. Maybe move it down if the logo is very large?
![Безымянный](https://user-images.githubusercontent.com/88277343/169636799-da1a1e02-5e56-40b4-8fc4-35b19aaca209.png)

**Comment by Botspot** [comment]
> @Botspot A large image "breaks" the description of the program. Maybe move it down if the logo is very large? ![Безымянный](https://user-images.githubusercontent.com/88277343/169636799-da1a1e02-5e56-40b4-8fc4-35b19aaca209.png)

I would have to make pi-apps install imagemagick on everyone's systems, then have the Details window check icon-64's dimensions for every app. This is the very definition of needless complexity! 😂
YouTubuddy's day has come. It will now be a 64x64 icon like everything else.

**Comment by Rak1ta** [comment]
It still happens. It turns out when switching tabs quickly, I don’t know how to get it!
[image](https://user-images.githubusercontent.com/88277343/169838154-141894f3-75df-43e5-bf27-486690741eb9.png)

**Comment by theofficialgman** [comment]
> It still happens. It turns out when switching tabs quickly, I don’t know how to get it! ![Безымянный16](https://user-images.githubusercontent.com/88277343/169838415-173574f7-7b21-46ba-9d7b-e436df7e3dda.png)

this is a limitation of the pipe. when you switch tabs without having finished loading the previous one, the data for the old tab it still loading in the pipe. its visual only and will be fixed if you wait for a tab to finish loading before switching

**Comment by Crilum** [comment]
My RPi 4 only does that after going back from the All Apps list, and even then it only loads the menu twice:
![image](https://user-images.githubusercontent.com/91354257/170385289-b735dae3-6f1a-4e64-ac30-e4b16865d511.png)

**Comment by Jai-JAP** [comment]
> My RPi 4 only does that after going back from the All Apps list before it loads (which happens in about 1 sec), and even then it only loads the menu twice:
> ![image](https://user-images.githubusercontent.com/91354257/170385289-b735dae3-6f1a-4e64-ac30-e4b16865d511.png)
> 

I too got similar error when i last tried new-gui just after it was released.
