### ISSUE TITLE
Ulauncher has huge frames

### ISSUE THREAD

**Issue by Rak1ta** [Botspot/pi-apps#2249]
### Confirmations

- [X] I searched for similar bug reports in https://github.com/Botspot/pi-apps/issues and found none were relevant.
- [X] I tried updating Pi Apps and the issue is still not fixed. [How to update Pi Apps?](https://github.com/Botspot/pi-apps#to-update-pi-apps)
- [X] IMPORTANT: I promise to respond to comments on this issue and write a good bug report https://www.softwaretestinghelp.com/how-to-write-good-bug-report/

### What happened?

Black borders around the edges of the program window

### Description

The problem is [described here](https://github.com/Ulauncher/Ulauncher/discussions/991
), but I don't want to break anything.
![Безымянный](https://user-images.githubusercontent.com/88277343/213867936-ac094a8b-62d7-4b3d-95f2-40253d5dc70b.png)

### What are your system specs (run the following command in your terminal)?

```bash
OS: Raspbian GNU/Linux 10 (buster)
OS architecture: 32-bit
Last updated Pi-Apps on: 01/21/2023
Latest Pi-Apps version: 01/21/2023
Kernel: armv7l 5.10.103-v7l+
Device model: Raspberry Pi 4 Model B Rev 1.2 
Cpu name: Cortex-A72
Ram size: 3.65 GB
Raspberry Pi OS image version: 2021-05-07
Language: en_US.UTF-8
```

### (Recommended) Error log? Terminal output? Debug messages?

```bash
pi@raspberrypi:~ $ env GDK_BACKEND=x11 /usr/bin/ulauncher --hide-window
DBus name already taken. Ulauncher is probably backgrounded. Did you mean `ulauncher-toggle`?
```

**Comment by theofficialgman** [comment]
oh yeah the default piOS DE on buster (lxde) doesn't come with a compositing window manager.
I assume when you run wite this `--no-window-shadow` there are no issues?

**Comment by Rak1ta** [comment]
@theofficialgman It got better, but the black frame is not completely gone.
![Безымянный](https://user-images.githubusercontent.com/88277343/213879744-6313e1e6-b589-49a7-990b-4de1506fc04a.png)

**Comment by theofficialgman** [comment]
yeah thats as good as its going to get
thats simply the window border

**Comment by Rak1ta** [comment]
@theofficialgman When uninstalling, I noticed that the program remains in a running state, but there is no longer any benefit from it. If possible, when deleting, make it close. Thanks!

**Comment by Botspot** [comment]
I think raspi-config has an option for enabling `xcompmgr`. That should fix it.

**Comment by Botspot** [comment]
> @theofficialgman When uninstalling, I noticed that the program remains in a running state, but there is no longer any benefit from it. If possible, when deleting, make it close. Thanks!

This is the case for most programs. For only a few apps have I explicitly told an app's `uninstall` script to kill any running instances of any app. Is there any particular reason why you feel the need for that to happen here, @Rak1ta?

**Comment by Rak1ta** [comment]
@Botspot The search command still works after removal, but does not work.  But there is no problem in the taskbar to close the application.

**Comment by Botspot** [comment]
This seems like standard behavior to me. But I understand it would be more intuitive for programs to close on uninstall.

If you would like to change all Pi-Apps `uninstall` scripts to do this, feel free to make a Pull Request!

**Comment by Rak1ta** [comment]
@Botspot If you can open a request.  Frame issue not resolved.

**Comment by Botspot** [comment]
> @Botspot If you can open a request? Frame issue not resolved.

Did enabling xcompmgr from raspi-config not fix it?

**Comment by Rak1ta** [comment]
@Botspot Turned it on, the `/etc/xdg/autostart/xcompmgr.desktop` file was created, rebooted. Frames are removed only with the `--no-window-shadow` command.

**Comment by Botspot** [comment]
@Rak1ta, I recall there being issues with default Raspbian Buster's xcompmgr config. Many people said that even when enabled in raspi-config, xcompmgr did not seem to do anything.

Here is one of many such reports: https://forums.raspberrypi.com/viewtopic.php?p=1844926&hilit=xcompmgr+buster#p1844961

Try **disabling** xcompmgr in raspi-config, then run `xcompmgr` in a terminal without any flags. I predict this will fix transparency for you.

**Comment by Rak1ta** [comment]
@Botspot There is a `raspi-config_20210212_all.deb` file which is my latest version. It has a file `.\usr\lib\raspi-config\cmstart.sh`
```
#!/bin/sh
if grep -q okay /proc/device-tree/soc/v3d@7ec00000/status 2> /dev/null || grep -q okay /proc/device-tree/soc/firmwarekms@7e600000/status 2> /dev/null ; then
    exec xcompmgr -aR
fi

```
With it, no changes in the operation of the system, transparency does not work. And in the console I run `xcompmgr` like for the first time.
```
pi@raspberrypi:~ $ xcompmgr
error 140: BadRegion request 138 minor 14 serial 12090
error 3: BadWindow (invalid Window parameter) request 20 minor 0 serial 13863
error 3: BadWindow (invalid Window parameter) request 15 minor 0 serial 13864
error 3: BadWindow (invalid Window parameter) request 2 minor 0 serial 13879
...
```
The [raspi-config repository](https://github.com/RPi-Distro/raspi-config/blob/e8d0a860ec4fcdfc1c7babf92497c630af531eff/usr/lib/raspi-config/cmstart.sh) (16.08.2021) has the same file with an additional fi that is not in the .deb.
```
#!/bin/sh
if grep -q okay /proc/device-tree/soc/v3d@7ec00000/status 2> /dev/null || grep -q okay /proc/device-tree/v3dbus/v3d@7ec04000/status 2> /dev/null || grep -q okay /proc/device-tree/soc/firmwarekms@7e600000/status 2> /dev/null ; then
    if ps ax | grep -v grep | grep -q openbox ; then
        exec xcompmgr -a
    fi
fi
```
In this case, the console writes that the program is running.
```
pi@raspberrypi:~ $ xcompmgr
Another composite manager is already running (xcompmgr)
```
But now xsnow overlays the desktop with a black background, while ulauncher continues to run with big black edges. It gives the same error as without running `xcompmgr` (error below as an example, if you run `xcompmgr` on your own from the console as before, then there will be no errors).
```
pi@raspberrypi:~ $ env GDK_BACKEND=x11 /usr/bin/ulauncher --no-window-shadow

(ulauncher:3716): Gdk-CRITICAL **: 11:57:06.972: gdk_window_thaw_toplevel_updates: assertion 'window->update_and_descendants_freeze_count > 0' failed
/usr/lib/python3/dist-packages/ulauncher/ui/windows/PreferencesUlauncherDialog.py:569: Warning: g_object_get_is_valid_property: object class 'GtkSettings' has no property named 'gtk-overlay-scrolling'
  self.webview.load_uri(uri)

(WebKitWebProcess:3748): GLib-GObject-WARNING **: 11:57:11.580: g_object_set_is_valid_property: object class 'GtkSettings' has no property named 'gtk-overlay-scrolling'
```
Guess something is not working, but I don't know why.

**Comment by Rak1ta** [comment]
@Botspot There is a `raspi-config_20210212_all.deb` file which is my latest version. It has a file `.\usr\lib\raspi-config\cmstart.sh`
```
#!/bin/sh
if grep -q okay /proc/device-tree/soc/v3d@7ec00000/status 2> /dev/null || grep -q okay /proc/device-tree/soc/firmwarekms@7e600000/status 2> /dev/null ; then
    exec xcompmgr -aR
fi

```
With it, no changes in the operation of the system, transparency does not work. And in the console I run `xcompmgr` like for the first time.
```
pi@raspberrypi:~ $ xcompmgr
error 140: BadRegion request 138 minor 14 serial 12090
error 3: BadWindow (invalid Window parameter) request 20 minor 0 serial 13863
error 3: BadWindow (invalid Window parameter) request 15 minor 0 serial 13864
error 3: BadWindow (invalid Window parameter) request 2 minor 0 serial 13879
...
```
The [raspi-config repository](https://github.com/RPi-Distro/raspi-config/blob/e8d0a860ec4fcdfc1c7babf92497c630af531eff/usr/lib/raspi-config/cmstart.sh) (16.08.2021) 
there is the same file with additional data, which is not in the .deb.
```
#!/bin/sh
if grep -q okay /proc/device-tree/soc/v3d@7ec00000/status 2> /dev/null || grep -q okay /proc/device-tree/v3dbus/v3d@7ec04000/status 2> /dev/null || grep -q okay /proc/device-tree/soc/firmwarekms@7e600000/status 2> /dev/null ; then
    if ps ax | grep -v grep | grep -q openbox ; then
        exec xcompmgr -a
    fi
fi
```
With this version of the file, the console writes that the program is running.
```
pi@raspberrypi:~ $ xcompmgr
Another composite manager is already running (xcompmgr)
```
But now `xsnow` overlays the desktop with a black background, while `ulauncher` continues to run with big black edges. It gives the same error as without running `xcompmgr` (error below as an example, if you run `xcompmgr` on your own from the console as before, then there will be no errors).
```
pi@raspberrypi:~ $ env GDK_BACKEND=x11 /usr/bin/ulauncher --no-window-shadow

(ulauncher:3716): Gdk-CRITICAL **: 11:57:06.972: gdk_window_thaw_toplevel_updates: assertion 'window->update_and_descendants_freeze_count > 0' failed
/usr/lib/python3/dist-packages/ulauncher/ui/windows/PreferencesUlauncherDialog.py:569: Warning: g_object_get_is_valid_property: object class 'GtkSettings' has no property named 'gtk-overlay-scrolling'
  self.webview.load_uri(uri)

(WebKitWebProcess:3748): GLib-GObject-WARNING **: 11:57:11.580: g_object_set_is_valid_property: object class 'GtkSettings' has no property named 'gtk-overlay-scrolling'
```
Guess something is not working, but I don't know why.

**Comment by Rak1ta** [comment]
env BAMF_DESKTOP_FILE_HINT=/var/lib/snapd/desktop/applications/chromium_chromium.desktop /snap/bin/chromium %U





@Botspot There is a `raspi-config_20210212_all.deb` file which is my latest version. It has a file `.\usr\lib\raspi-config\cmstart.sh`
```
#!/bin/sh
if grep -q okay /proc/device-tree/soc/v3d@7ec00000/status 2> /dev/null || grep -q okay /proc/device-tree/soc/firmwarekms@7e600000/status 2> /dev/null ; then
    exec xcompmgr -aR
fi

```
With it, no changes in the operation of the system, transparency does not work. And in the console I run `xcompmgr` like for the first time.
```
pi@raspberrypi:~ $ xcompmgr
error 140: BadRegion request 138 minor 14 serial 12090
error 3: BadWindow (invalid Window parameter) request 20 minor 0 serial 13863
error 3: BadWindow (invalid Window parameter) request 15 minor 0 serial 13864
error 3: BadWindow (invalid Window parameter) request 2 minor 0 serial 13879
...
```
The [raspi-config repository](https://github.com/RPi-Distro/raspi-config/blob/e8d0a860ec4fcdfc1c7babf92497c630af531eff/usr/lib/raspi-config/cmstart.sh) (16.08.2021) 
there is a modified file, I have FKMS enabled, I hoped it would work (
at least some changes were with this commit).
```
#!/bin/sh
if grep -q okay /proc/device-tree/soc/v3d@7ec00000/status 2> /dev/null || grep -q okay /proc/device-tree/v3dbus/v3d@7ec04000/status 2> /dev/null || grep -q okay /proc/device-tree/soc/firmwarekms@7e600000/status 2> /dev/null ; then
    if ps ax | grep -v grep | grep -q openbox ; then
        exec xcompmgr -a
    fi
fi
```
With this version of the file, the console writes that the program is running.
```
pi@raspberrypi:~ $ xcompmgr
Another composite manager is already running (xcompmgr)
```
But now `xsnow` overlays the desktop with a black background, while `ulauncher` continues to run with big black edges. It gives the same error as without running `xcompmgr` (error below as an example, if you run `xcompmgr` on your own from the console as before, then there will be no errors).
```
pi@raspberrypi:~ $ env GDK_BACKEND=x11 /usr/bin/ulauncher --no-window-shadow

(ulauncher:3716): Gdk-CRITICAL **: 11:57:06.972: gdk_window_thaw_toplevel_updates: assertion 'window->update_and_descendants_freeze_count > 0' failed
/usr/lib/python3/dist-packages/ulauncher/ui/windows/PreferencesUlauncherDialog.py:569: Warning: g_object_get_is_valid_property: object class 'GtkSettings' has no property named 'gtk-overlay-scrolling'
  self.webview.load_uri(uri)

(WebKitWebProcess:3748): GLib-GObject-WARNING **: 11:57:11.580: g_object_set_is_valid_property: object class 'GtkSettings' has no property named 'gtk-overlay-scrolling'
```
Guess something is not working, but I don't know why.

**Comment by Rak1ta** [comment]
@Botspot There is a `raspi-config_20210212_all.deb` file which is my latest version. It has a file `.\usr\lib\raspi-config\cmstart.sh`
```
#!/bin/sh
if grep -q okay /proc/device-tree/soc/v3d@7ec00000/status 2> /dev/null || grep -q okay /proc/device-tree/soc/firmwarekms@7e600000/status 2> /dev/null ; then
    exec xcompmgr -aR
fi

```
With it, no changes in the operation of the system, transparency does not work. And in the console I run `xcompmgr` like for the first time.
```
pi@raspberrypi:~ $ xcompmgr
error 140: BadRegion request 138 minor 14 serial 12090
error 3: BadWindow (invalid Window parameter) request 20 minor 0 serial 13863
error 3: BadWindow (invalid Window parameter) request 15 minor 0 serial 13864
error 3: BadWindow (invalid Window parameter) request 2 minor 0 serial 13879
...
```
The [raspi-config repository](https://github.com/RPi-Distro/raspi-config/blob/e8d0a860ec4fcdfc1c7babf92497c630af531eff/usr/lib/raspi-config/cmstart.sh) (16.08.2021) there is a modified file, I have FKMS enabled, I hoped it would work (at least some changes were with this commit).
```
#!/bin/sh
if grep -q okay /proc/device-tree/soc/v3d@7ec00000/status 2> /dev/null || grep -q okay /proc/device-tree/v3dbus/v3d@7ec04000/status 2> /dev/null || grep -q okay /proc/device-tree/soc/firmwarekms@7e600000/status 2> /dev/null ; then
    if ps ax | grep -v grep | grep -q openbox ; then
        exec xcompmgr -a
    fi
fi
```
With this version of the file, the console writes that the program is running.
```
pi@raspberrypi:~ $ xcompmgr
Another composite manager is already running (xcompmgr)
```
But now `xsnow` overlays the desktop with a black background, while `ulauncher` continues to run with big black edges. It gives the same error as without running `xcompmgr` (error below as an example, if you run `xcompmgr` on your own from the console as before, then there will be no errors).
```
pi@raspberrypi:~ $ env GDK_BACKEND=x11 /usr/bin/ulauncher --no-window-shadow

(ulauncher:3716): Gdk-CRITICAL **: 11:57:06.972: gdk_window_thaw_toplevel_updates: assertion 'window->update_and_descendants_freeze_count > 0' failed
/usr/lib/python3/dist-packages/ulauncher/ui/windows/PreferencesUlauncherDialog.py:569: Warning: g_object_get_is_valid_property: object class 'GtkSettings' has no property named 'gtk-overlay-scrolling'
  self.webview.load_uri(uri)

(WebKitWebProcess:3748): GLib-GObject-WARNING **: 11:57:11.580: g_object_set_is_valid_property: object class 'GtkSettings' has no property named 'gtk-overlay-scrolling'
```
Guess something is not working, but I don't know why.

**Comment by Rak1ta** [comment]
@Botspot If you remove the `-aR` arguments in `/usr/lib/raspi-config/cmstart.sh`, then transparency works fine. And in the terminal, when I try to run it, it shows that `xcompmgr` is already running. But I do not know how it can affect performance. Sorry if you received a lot of notifications. I deleted the post a couple of times.
![Безымянный](https://user-images.githubusercontent.com/88277343/214027862-415cccc2-75d7-4cb7-8845-ac189ceacf6a.png)

with argument R
```
pi@raspberrypi:~ $ xcompmgr
error 140: BadRegion request 138 minor 14 serial 12090
error 3: BadWindow (invalid Window parameter) request 20 minor 0 serial 13863
...
```

no arguments
```
pi@raspberrypi:~ $ xcompmgr
Another composite manager is already running (xcompmgr)
```

```
-a
      Use automatic server-side compositing. Faster, but no special effects.
   -R
      Run, but do not explicitly register compositing manager with X.
```
