### ISSUE TITLE
Minecraft Bedrock recent Bookworm update - MS login still broken - frustrating system pollution with unnecessary armhf libs

### ISSUE THREAD

**Issue by bagong** [Botspot/pi-apps#2485]
### Confirmations

- [X] I searched for similar bug reports in https://github.com/Botspot/pi-apps/issues and found none were relevant.
- [X] I tried updating Pi-Apps and the issue is still not fixed. [How to update Pi-Apps?](https://pi-apps.io/wiki/getting-started/updating-pi-apps/)
- [X] IMPORTANT: I promise to respond to comments on this issue and write a good bug report https://www.softwaretestinghelp.com/how-to-write-good-bug-report/

### What happened?

webengine-browser comes up but doesn't load xbox login window

### Description

This is mainly a frustrated report prompted by lazy handling of updates and bugfixes done to help pi-apps maintainers: the MC Bedrock installer continues to pollute arm64 systems with totally unnecessary armhf libraries, even worse, the installer somehow creates a system state that blocks removal of architecture armhf because some libs cannot be uninstalled any more.
Additionally the MS login fail must be caused by some settings done by pi-apps, be it environment variables or installed libs that override the AppImg. A login attempt creates a state in which neither the browser-winow nor minecraft can be closed - this will be really frustrating for novice users. After really being furious about the armhf pollution I totally reset the system from scratch, just to find that the bare downloaded AppImg + libfuse2 started just fine from the command line and allowed both logins with no hickups whatsoever... no tricks required. 
If you have 2 people really look into a problem manifesting in Piapps, you should honour those efforts with more than keeping your old installer just as dirty as it was before, although there have been complaints long ago.

### What are your system specs (run the following command in your terminal)?

```bash
Bookworm
64-bit
Installed from scratch today.
```

**Comment by theofficialgman** [comment]
I ran the CI which uses true fresh images. No issues on any distro https://github.com/Botspot/pi-apps/actions/runs/6974181169

I will note that armhf multiarch is necessary to support older versions of Minecraft which is only available for armhf. The Minecraft bedrock Linux launcher recommends this and we have always done so.

Login was tested without any issues.

So please submit logs.

**Comment by theofficialgman** [comment]
> the installer somehow creates a system state that blocks removal of architecture armhf because some libs cannot be uninstalled any more.

`purge_packages` was forgotten in the uninstaller. I did not write the script originally so did not check. It has been corrected https://github.com/Botspot/pi-apps/commit/9c637207c1449358bf665426b6ead6a6fcc0a930

**Comment by theofficialgman** [comment]
>  webengine-browser comes up but doesn't load xbox login window
> ...
> Additionally the MS login fail must be caused by some settings done by pi-apps, be it environment variables or installed libs that override the AppImg.

refer to commit history for why environment variables were added https://github.com/Botspot/pi-apps/commit/f6a115943b30bf1705f1f5a1ac4d038d7e61f1fa

**Comment by theofficialgman** [comment]
> ### What are your system specs (run the following command in your terminal)?
> ```shell
> Bookworm
> 64-bit
> Installed from scratch today.
> ```

invalid response. we ask for the output from `~/pi-apps/api get_device_info` for a reason. it is not a suggestion.

**Comment by NickZimm** [comment]
I was having a similar problem to this. Could not get the microsoft log-in page to correctly open. Black screen, unclosable.
Tried running in terminal then instead of using microsoft log-in buttons, opened marketplace. I log-in there just fine. You can then return to game screen and play on active servers. Hope this helps.

**Comment by theofficialgman** [comment]
@NickZimm please open a bug report issue if you are having trouble. This issue has been resolved and you have not provided required info that would be asked in our bug report template.

Regardless it's likely a Microsoft/upstream bug that cannot be resolved by us but it helps to open an issue anyway so it can be tracked

**Comment by Botspot** [comment]
It seems that the microsoft login now works, according to somebody on the pi forums. https://forums.raspberrypi.com/viewtopic.php?p=2200744#p2200744
Linking this here in case anyone else reports the issue

**Comment by bagong** [comment]
The problem - or an unsolved problem - is that the arguments used to start the appimage used *in your launcher* prevents the login screen from appearing. Once a successful login on a system has occurred, subsequent under the hood logins will succeed. The workaround is to start the appimage once manually and run the login procedure. For subsequent runs the launcher integrated into the desktop can be used as the login dialogue is not required any more. You can verify that only by testing on a clean system. While it is a minor inconvenience for people in the know, it's fatal for people who don't understand what is going on. And testers who just install on top of an old install won't bump into the problem either because the preexisting login info is used.

**Comment by Botspot** [comment]
@bagong, please pardon my unfamiliarity with this app. I do not have an account with this game purchased. Without an account, is it possible to trigger the issue? I tried to cause the black, unclosable window to occur, but did not see the option to sign in with Microsoft anywhere, just Google, which seemed to work fine.

In other words, would you mind explaining a bit more in depth *exactly what is necessary* to reproduce this issue? That would help a lot. The flags were [added](https://github.com/Botspot/pi-apps/commit/f6a115943b30bf1705f1f5a1ac4d038d7e61f1fa) by @theofficialgman to work around a bug in PiOS Bullseye. I am not familiar with the details around that.

**Comment by bagong** [comment]
Handling this issue (and the bedrock linux launcher) within pi-apps has a long back story and I am tired of doing the time consuming testing work and then seeing that the issue isn't fixed properly. But for your understanding: the MS login is a second login occurring from within MC. It used to be optional, but (at least at some point) it was enforced at least for network-gaming. The login button is visible on the MC welcome screen (not the launcher's) to the left of the large, central buttons. You can also trigger the login from within the MC options. I don't remember at which point of the login process the error occurs, but I think no actual MS issued MC license is required, as you acquired a license through Google Play, so any MS account should work. Things might have changed, however.

**Comment by theofficialgman** [comment]
> I am tired of doing the time consuming testing work and then seeing that the issue isn't fixed properly

yes me too but unfortunately these things are typically out of our control and caused by changes at the bedrock launcher (changes in QT webview chromium version) and system drivers (raspberry pi foundation updates). I have removed the flags. Refer to the commit message for more detail https://github.com/Botspot/pi-apps/commit/0da589179a798a421dbc66733b3a95024a84dc78
