### ISSUE TITLE
unrar for raspberry pi (armhf)

### ISSUE THREAD

**Issue by fabianmendes** [Botspot/pi-apps#255]
Due to was not an easy installation, I've decided to create an app. I bright it here because installing it is not pleasant as it should be just adding the deb source into the sources.list (because the public key is not there), and just installing the unrar.deb is quite lame because of its dependencies, and they are not aptitude installable either! [unrar.zip](https://github.com/Botspot/pi-apps/files/5825692/unrar.zip)
![unrar-logo](https://user-images.githubusercontent.com/31230743/104833805-df8c6180-5871-11eb-9c8a-6e0583c5e31d.png)

**Comment by Itai-Nelken** [comment]
question: why use gdebi?
I just see a lot of tutorials install gdebi instead of using `sudo dpkg -i filename.deb` or `sudo apt install ./filename.deb`, and I would like to know why.

**Comment by fabianmendes** [comment]
I found it easier to work with, but if you prefer, feel free to change it.
That's the way how I worked for me on the first try!
 ~V. Fabian T· Mendes C.

**Comment by fabianmendes** [comment]
> question: why use gdebi?
> I just see a lot of tutorials install gdebi instead of using `sudo dpkg -i filename.deb` or `sudo apt install ./filename.deb`, and I would like to know why.

I've just seen that `sudo gdebi  file.deb **-y**` won't work.

**Comment by Itai-Nelken** [comment]
> I found it easier to work with, but if you prefer, feel free to change it. That's the way how it worked for me on the first try!

If it works then great! I just think its an unnecessary dependency. and if it doesn't have any special feature that makes it work, I don't see the point in using it when you can use what is already installed.

here is a version using apt instead of gdebi, also the uninstall script is blank:
[unrar.zip](https://github.com/Botspot/pi-apps/files/5825704/unrar.zip)

also @Botspot maybe add a feature to `pkg-install` that allows it to install dependencies from sources other than the apt repos.

**Comment by fabianmendes** [comment]
> @fabianmendes here is a version using apt instead of gdebi, also the uninstall script is blank:
> [unrar.zip](https://github.com/Botspot/pi-apps/files/5825704/unrar.zip)
> 
 Ok, I will look into it. Thanks!

**Comment by fabianmendes** [comment]
@Itai-Nelken , I got this 
![2021-01-20-091247_800x480_scrot](https://user-images.githubusercontent.com/31230743/105179475-c567b300-5aff-11eb-87a7-e74d4873e985.png)

```
--2021-01-20 09:12:44--  http://ftp.br.debian.org/debian/pool/main/g/gcc-10/libgcc-s1.2.1-6_armhf.deb
Resolviendo ftp.br.debian.org (ftp.br.debian.org)... 200.236.31.3, 2801:82:80ff:8000::4
Conectando con ftp.br.debian.org (ftp.br.debian.org)[200.236.31.3]:80... conectado.
Petición HTTP enviada, esperando respuesta... 404 Not Found
2021-01-20 09:12:44 ERROR 404: Not Found.

```

**Comment by Itai-Nelken** [comment]
@fabianmendes that is because that link doesn't work.

**Comment by fabianmendes** [comment]
> @Itai-Nelken , I got this
> --2021-01-20 09:12:44--  http://ftp.br.debian.org/debian/pool/main/g/gcc-10/libgcc-s1.2.1-6_armhf.deb
> Resolviendo ftp.br.debian.org (ftp.br.debian.org)... 200.236.31.3, 2801:82:80ff:8000::4
> Conectando con ftp.br.debian.org (ftp.br.debian.org)[200.236.31.3]:80... conectado.
> Petición HTTP enviada, esperando respuesta... 404 Not Found
> 2021-01-20 09:12:44 ERROR 404: Not Found.
> ```
(I didn't purge anything, btw)
I saw the error, was my fault.
It should be:
http://ftp.br.debian.org/debian/pool/main/g/gcc-10/ **libgcc-s1_10**.2.1-6_armhf.deb
Instead of:
http://ftp.br.debian.org/debian/pool/main/g/gcc-10/ **libgcc-s1**.2.1-6_armhf.deb

**Comment by fabianmendes** [comment]
Done!! It works @Botspot! [unrar.zip](https://github.com/Botspot/pi-apps/files/5842710/unrar.zip)

![2021-01-20-092643_800x480_scrot](https://user-images.githubusercontent.com/31230743/105181104-c4378580-5b01-11eb-859c-0fdac9adef56.png)

**Comment by Botspot** [comment]
It failed to install for me.  
[unrar_output_log.txt](https://github.com/Botspot/pi-apps/files/5890711/unrar_output_log.txt)

**Comment by fabianmendes** [comment]
Mhm, I forgot to add the link for the installation of *libc6-armhf-cross*
link for the wget:
http://ftp.br.debian.org/debian/pool/main/c/cross-toolchain-base/libc6-armhf-cross_2.28-7cross1_all.deb

Thanks Botspot. If failed again, please share to me the log again.

 ~V. Fabian T· Mendes C.

**Comment by Botspot** [comment]
```
Note, selecting 'libc6-armhf-cross' instead of './libc6-armhf-cross_2.28-7cross1_all.deb'
The following NEW packages will be installed:
  libc6-armhf-cross
0 upgraded, 1 newly installed, 0 to remove and 0 not upgraded.
Need to get 1,170 kB of archives.
After this operation, 0 B of additional disk space will be used.
Get:1 http://mirror.pit.teraswitch.com/raspbian/raspbian buster/main armhf libc6-armhf-cross all 2.28-7cross1 [1,170 kB]
Fetched 1,170 kB in 1s (954 kB/s)           
Selecting previously unselected package libc6-armhf-cross.
(Reading database ... 271330 files and directories currently installed.)
Preparing to unpack .../libc6-armhf-cross_2.28-7cross1_all.deb ...
Unpacking libc6-armhf-cross (2.28-7cross1) ...
Setting up libc6-armhf-cross (2.28-7cross1) ...
Reading package lists... Done
Building dependency tree       
Reading state information... Done
Note, selecting 'libgcc-s1-armhf-cross' instead of './libgcc-s1-armhf-cross_10.2.1-6cross1_all.deb'
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies:
 libgcc-s1-armhf-cross : Depends: libc6-armhf-cross (>= 2.31) but 2.28-7cross1 is to be installed
E: Unable to correct problems, you have held broken packages.
Failed to installing dependency: libgcc-s1-armhf-cross

Failed to install unrar with install-32 script!
```
Looks like we need a later version of libc6-armhf-cross for it to work.

**Comment by fabianmendes** [comment]
Mhm let me see on my raspberry. It works on mine, give me a several minutes
cuz I'm on something else. Thanks!

**Comment by fabianmendes** [comment]
> Mhm, I forgot to add the link for the installation of *libc6-armhf-cross* link for the wget: http://ftp.br.debian.org/debian/pool/main/c/cross-toolchain-base/libc6-armhf-cross_2.28-7cross1_all.deb Thanks Botspot. If failed again, please share to me the log again. ~V. Fabian T· Mendes C. El jue, 28 ene 2021 a las 19:58, Botspot (<notifications@github.com>)

Did you download it from that URL?

Maybe you need this too `wget http://ftp.br.debian.org/debian/pool/main/c/cross-toolchain-base/linux-libc-dev-armhf-cross_4.19.20-1cross1_all.deb`
I don't remember, but I guess yes. (I have it installed)

**Comment by fabianmendes** [comment]
> > Mhm, I forgot to add the link for the installation of _libc6-armhf-cross_ link for the wget: http://ftp.br.debian.org/debian/pool/main/c/cross-toolchain-base/libc6-armhf-cross_2.28-7cross1_all.deb Thanks Botspot. If failed again, please share to me the log again. ~V. Fabian T· Mendes C. El jue, 28 ene 2021 a las 19:58, Botspot ([notifications@github.com](mailto:notifications@github.com))
> 
> Did you download it from that URL?
> 
> Maybe you need this too `wget http://ftp.br.debian.org/debian/pool/main/c/cross-toolchain-base/linux-libc-dev-armhf-cross_4.19.20-1cross1_all.deb`
> I don't remember, but I guess yes. (I have it installed)

@Itai-Nelken may you please help me? I don't know exactly how to run a `.deb` file without using `gdebi`
Otherwise, @Botspot, could you add that line above quoted? Seems to it may be missing and as a dependency that should be why you could install it. I have it installed and works perfectly, bro. And once install-32 is done, I will learn from your script to update the app to have an install-64 script as well (I can do it to contribute to the work and save you time -I hope so).

PS: I'm into the _Unreal for RPi4_'s script. Hope you all are having happy holidays!

**Comment by Itai-Nelken** [comment]
>@Itai-Nelken may you please help me? I don't know exactly how to run a .deb file without using gdebi

@fabianmendes you can install deb packages in 2 ways:
1) `sudo dpkg -i file.deb`
2) `sudo apt install ./file.deb`
for option 2 you can add the `-f` option so it fixes any missing dependencies and the `-y` option so it doesn't ask you any questions.
**Simply put:** `sudo apt -f -y install ./file.deb`

**Comment by fabianmendes** [comment]
Done @Botspot 
[unrar.zip](https://github.com/Botspot/pi-apps/files/6012989/unrar.zip) !
32 Only for now, I will create my 64-bit setup later for Unreal installation and then I will create the 64-bit version of this app (unrar)

**Comment by Botspot** [comment]
> Done @Botspot
> [unrar.zip](https://github.com/Botspot/pi-apps/files/6012989/unrar.zip) !
> 32 Only for now, I will create my 64-bit setup later for Unreal installation and then I will create the 64-bit version of this app (unrar)

How is progress on the 64-bit version, and could we elaborate the description?

**Comment by fabianmendes** [comment]
> > Done @Botspot
> > [unrar.zip](https://github.com/Botspot/pi-apps/files/6012989/unrar.zip) !
> > 32 Only for now, I will create my 64-bit setup later for Unreal installation and then I will create the 64-bit version of this app (unrar)
> 
> How is progress on the 64-bit version, and could we elaborate the description?

See [unrar.zip](https://github.com/Botspot/pi-apps/files/6138877/unrar.zip), please try it out (also, I've created a description, hope that's enough.

**Comment by Botspot** [comment]
> See [unrar.zip](https://github.com/Botspot/pi-apps/files/6138877/unrar.zip), please try it out (also, I've created a description, hope that's enough.

The description is still the same:

> urar as all we know, on your terminal.
> 
> HOW TO RUN: Go to> your terminal> "cd" to desire folder, and write: "unrar x file.rar"

Remember, the first line is the tooltip text that appears when your mouse hovers over the app. (in the list of apps)  
I think anybody who doesn't already know what unrar is, will not be benefited by reading "urar as all we know, on your terminal."

Perhaps: "Utility to extract .rar files"

**Comment by fabianmendes** [comment]
Oh sorry OKok right haha, thanks

**Comment by Botspot** [comment]
> Oh sorry OK ok right haha thanks

Would you like to edit the description, or should I give it a try?

**Comment by fabianmendes** [comment]
Yes, please go Forward to it! And sorry about that

On Mar 16, 2021 4:37 PM, "Botspot" ***@***.***> wrote:

Oh sorry OK ok right haha thanks

Would you like to edit the description, or should I give it a try?

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/Botspot/pi-apps/issues/255#issuecomment-800587132>, or
unsubscribe

**Comment by Botspot** [comment]
@fabianmendes I just noticed something:
```
pi@raspberrypi:~ $ apt search unrar
Sorting... Done
Full Text Search... Done

unp/stable 2.0~pre7+nmu1 all
  unpack (almost) everything with one command

unrar-free/stable 1:0.0.1+cvs20140707-4 armhf
  Unarchiver for .rar files
```
Do you see what I see? Looks like it was possible all along to `sudo apt install unrar-free` to be able to extract .rar files.

Am I missing something here?

**Comment by locness3** [comment]
> Looks like it was possible all along to sudo apt install unrar-free to be able to extract .rar files.

Seems like this works.
