### ISSUE TITLE
[Beta release] MS account support for Minecraft Java

### ISSUE THREAD

**Issue by mobilegmYT** [Botspot/pi-apps#483]
NOTE: THIS IS HIGHLY EXPERIMENTAL AND MAY HAVE ISSUES. PLEASE REPORT BUGS IF YOU FIND THEM

Extract the zip to `~/pi-apps/apps/` and open pi-apps and install ~ATLauncher~ Lunar Client

~~[ATLauncher.zip](https://github.com/Botspot/pi-apps/files/6174899/ATLauncher.zip)~~

**(scroll down to bottom of page to find latest version of installer, now on lunar client instead of atlauncher)**

**Comment by PythonJoshua** [comment]
downloaded successful but i cant find out where to open it, if its from the games section it says

invalid desktop entry file: '/home/pi/.local/share/applications/MinecraftLauncher.desktop'

**Comment by Itai-Nelken** [comment]
@PythonJoshua run `cat /home/pi/.local/share/applications/MinecraftLauncher.desktop`

**Comment by PythonJoshua** [comment]
> @PythonJoshua run `cat /home/pi/.local/share/applications/MinecraftLauncher.desktop`

```[Desktop Entry]
Version=1.0
Type=Application
Name=Minecraft Launcher
Comment=3D block based sandbox game
Icon=ATlauncher
Exec=~/Minecraft/LaunchATLAuncher.sh
Categories=Game;
```

**Comment by Itai-Nelken** [comment]
> ~/Minecraft/LaunchATLAuncher.sh

@PythonJoshua run `~/Minecraft/LaunchATLAuncher.sh`

**Comment by PythonJoshua** [comment]
> > ~/Minecraft/LaunchATLAuncher.sh
> 
> @PythonJoshua run `~/Minecraft/LaunchATLAuncher.sh`

bash: /home/pi/Minecraft/LaunchATLAuncher.sh: Permission denied

**Comment by Itai-Nelken** [comment]
> bash: /home/pi/Minecraft/LaunchATLAuncher.sh: Permission denied

@PythonJoshua `sudo chmod +x ~/Minecraft/LaunchATLAuncher.sh` and run again.
@mobilegmYT your script should make that script executable.

**Comment by PythonJoshua** [comment]
> sudo chmod +x ~/Minecraft/LaunchATLAuncher.sh

works, thank you so much!

**Comment by mobilegmYT** [comment]
> > bash: /home/pi/Minecraft/LaunchATLAuncher.sh: Permission denied
> 
> @PythonJoshua `sudo chmod +x ~/Minecraft/LaunchATLAuncher.sh` and run again.
> @mobilegmYT your script should make that script executable.

[ATLauncher.zip](https://github.com/Botspot/pi-apps/files/6175742/ATLauncher.zip)

**Comment by mobilegmYT** [comment]
Fixed internal errors

[ATLauncher.zip](https://github.com/Botspot/pi-apps/files/6175922/ATLauncher.zip)

**Comment by scamdotnet** [comment]
The uninstall script needs to be made executable. If you have an existing version, use `sudo chmod +x ~/pi-apps/apps/ATLauncher/uninstall`

**Comment by mobilegmYT** [comment]
> The uninstall script needs to be made executable. If you have an existing version, use `sudo chmod +x ~/pi-apps/apps/ATLauncher/uninstall`

[ATLauncher.zip](https://github.com/Botspot/pi-apps/files/6176015/ATLauncher.zip)

**Comment by mobilegmYT** [comment]
[ATLauncher.zip](https://github.com/Botspot/pi-apps/files/6176031/ATLauncher.zip)

**Comment by gl91306** [comment]
nice: ‘/home/pi/pi-apps/apps/ATLauncher/install’: Permission denied

**Comment by mobilegmYT** [comment]
> nice: ‘/home/pi/pi-apps/apps/ATLauncher/install’: Permission denied

Just a issue with the beta. See https://github.com/Botspot/pi-apps/issues/483#issuecomment-803294015

**Comment by pi-dev500** [comment]
My script is not working with the detection of ATlauncher profiles but it modify the java interpreter.

```
wget -qO- https://raw.githubusercontent.com/pi-dev500/MinecraftMicrosoftPILauncher/main/pre-release/setupATpi.sh | bash
 ```

**Comment by scamdotnet** [comment]
> My script is not working with the detection of ATlauncher profiles but it modify the java interpreter.
> 
> ```
> wget -qO- https://raw.githubusercontent.com/pi-dev500/MinecraftMicrosoftPILauncher/main/pre-release/setupATpi.sh | bash
> ```

```
I tried this out and here is my result (note that it says invalid java path):
[24/03/2021 09:10:00 AM] Organising filesystem
[24/03/2021 09:10:00 AM] Custom Java Path Is Incorrect! Defaulting to valid value!
[24/03/2021 09:10:00 AM] Tried to allocate 2048MB of maximum memory but only 1024MB is available to use!
[24/03/2021 09:10:01 AM] ATLauncher Version: 3.4.3.1
[24/03/2021 09:10:01 AM] Java Version: Launcher: Java 8 (1.8.0_251), Minecraft: Java 11 (11.0.9.1)
[24/03/2021 09:10:01 AM] Java Path: /usr/lib/jvm/java-11-openjdk-armhf
[24/03/2021 09:10:01 AM] 64 Bit Java: false
[24/03/2021 09:10:01 AM] RAM Available: 1024MB
[24/03/2021 09:10:01 AM] Launcher Directory: **USERSDIR**
[24/03/2021 09:10:01 AM] GPU: unknown (unknown) unknown 0MB VRAM
[24/03/2021 09:10:02 AM] CPU: 1 cores/4 threads
[24/03/2021 09:10:02 AM] Operating System: Raspbian GNU/Linux (10 (buster) build 5.10.17-v7l+)
[24/03/2021 09:10:02 AM] Bitness: 32
[24/03/2021 09:10:02 AM] Uptime: 479
[24/03/2021 09:10:02 AM] Manufacturer: GNU/Linux
[24/03/2021 09:10:03 AM] Disk: / (24234 MB Free)
[24/03/2021 09:10:03 AM] Disk: /dev/mmcblk0p1 (204 MB Free)
[24/03/2021 09:10:03 AM] Disk: /dev/sda2 (5863 MB Free)
[24/03/2021 09:10:03 AM] Disk: /dev/sda1 (198 MB Free)
[24/03/2021 09:10:03 AM] Showing splash screen and loading everything
[24/03/2021 09:10:03 AM] Checking for updated files!
[24/03/2021 09:10:09 AM] Finished downloading updated files!
[24/03/2021 09:10:10 AM] Launcher finished loading everything
[24/03/2021 09:10:10 AM] Failed to initialize Discord integration
[24/03/2021 09:10:10 AM] java.lang.UnsatisfiedLinkError: /home/pi/.discord-rpc/libdiscord-rpc.so: /home/pi/.discord-rpc/libdiscord-rpc.so: wrong ELF class: ELFCLASS64 (Possible cause: architecture word width mismatch)
	at java.lang.ClassLoader$NativeLibrary.load(Native Method)
	at java.lang.ClassLoader.loadLibrary0(ClassLoader.java:1934)
	at java.lang.ClassLoader.loadLibrary(ClassLoader.java:1817)
	at java.lang.Runtime.load0(Runtime.java:809)
	at java.lang.System.load(System.java:1086)
	at net.arikia.dev.drpc.DiscordRPC.loadDLL(DiscordRPC.java:159)
	at net.arikia.dev.drpc.DiscordRPC.<clinit>(DiscordRPC.java:21)
	at com.atlauncher.App.main(App.java:389)
[24/03/2021 09:10:10 AM] Launcher opening
[24/03/2021 09:10:10 AM] Made By Bob*
[24/03/2021 09:10:10 AM] *(Not Actually)
[24/03/2021 09:10:10 AM] Setting up Bottom Bar
[24/03/2021 09:10:10 AM] Finished Setting up Bottom Bar
[24/03/2021 09:10:10 AM] Setting up Tabs
[24/03/2021 09:10:12 AM] Finished Setting up Tabs
[24/03/2021 09:10:12 AM] Showing Launcher
[24/03/2021 09:10:59 AM] Logging into Minecraft!
[24/03/2021 09:11:00 AM] Added Mojang Account Scamdotnet
[24/03/2021 09:11:00 AM] Changed account to Scamdotnet
[24/03/2021 09:11:01 AM] Downloading skin for Scamdotnet
[24/03/2021 09:11:07 AM] Started install of Vanilla Minecraft version 1.16.5
[24/03/2021 09:15:40 AM] Preparing for launch!
[24/03/2021 09:16:12 AM] Launching pack Vanilla Minecraft 1.16.5 for Minecraft 1.16.5
[24/03/2021 09:16:12 AM] Logging into Minecraft!
[24/03/2021 09:16:12 AM] Trying to login with access token!
[24/03/2021 09:16:13 AM] Launching Minecraft with the following arguments (user related stuff has been removed): [/usr/lib/jvm/java-11-openjdk-armhf/bin/java, -XX:-OmitStackTraceInFastThrow, -Xms512M, -Xmx1024M, -XX:MetaspaceSize=256M, -Duser.language=en, -Duser.country=US, -Dfml.log.level=INFO, -Dorg.lwjgl.librarypath=/home/pi/.local/share/ATlauncher/lwjgl, -XX:+UseConcMarkSweepGC, -XX:+CMSIncrementalMode, -XX:-UseAdaptiveSizePolicy, -Xmn128M, -Xss1M, -Djava.library.path=USERSDIR/temp/natives-32dc105b60514ec1b318bd744c087902, -Dminecraft.launcher.brand=ATLauncher, -Dminecraft.launcher.version=3.4.3.1, -Djava.library.path=USERSDIR/temp/natives-32dc105b60514ec1b318bd744c087902, -cp, USERSDIR/libraries/net/minecraft/client/1.16.5/client-1.16.5.jar:USERSDIR/libraries/com/mojang/patchy/1.1/patchy-1.1.jar:USERSDIR/libraries/oshi-project/oshi-core/1.1/oshi-core-1.1.jar:USERSDIR/libraries/net/java/dev/jna/jna/4.4.0/jna-4.4.0.jar:USERSDIR/libraries/net/java/dev/jna/platform/3.4.0/platform-3.4.0.jar:USERSDIR/libraries/com/ibm/icu/icu4j/66.1/icu4j-66.1.jar:USERSDIR/libraries/com/mojang/javabridge/1.0.22/javabridge-1.0.22.jar:USERSDIR/libraries/net/sf/jopt-simple/jopt-simple/5.0.3/jopt-simple-5.0.3.jar:USERSDIR/libraries/io/netty/netty-all/4.1.25.Final/netty-all-4.1.25.Final.jar:USERSDIR/libraries/com/google/guava/guava/21.0/guava-21.0.jar:USERSDIR/libraries/org/apache/commons/commons-lang3/3.5/commons-lang3-3.5.jar:USERSDIR/libraries/commons-io/commons-io/2.5/commons-io-2.5.jar:USERSDIR/libraries/commons-codec/commons-codec/1.10/commons-codec-1.10.jar:USERSDIR/libraries/net/java/jinput/jinput/2.0.5/jinput-2.0.5.jar:USERSDIR/libraries/net/java/jutils/jutils/1.0.0/jutils-1.0.0.jar:USERSDIR/libraries/com/mojang/brigadier/1.0.17/brigadier-1.0.17.jar:USERSDIR/libraries/com/mojang/datafixerupper/4.0.26/datafixerupper-4.0.26.jar:USERSDIR/libraries/com/google/code/gson/gson/2.8.0/gson-2.8.0.jar:USERSDIR/libraries/com/mojang/authlib/2.1.28/authlib-2.1.28.jar:USERSDIR/libraries/org/apache/commons/commons-compress/1.8.1/commons-compress-1.8.1.jar:USERSDIR/libraries/org/apache/httpcomponents/httpclient/4.3.3/httpclient-4.3.3.jar:USERSDIR/libraries/commons-logging/commons-logging/1.1.3/commons-logging-1.1.3.jar:USERSDIR/libraries/org/apache/httpcomponents/httpcore/4.3.2/httpcore-4.3.2.jar:USERSDIR/libraries/it/unimi/dsi/fastutil/8.2.1/fastutil-8.2.1.jar:USERSDIR/libraries/org/apache/logging/log4j/log4j-api/2.8.1/log4j-api-2.8.1.jar:USERSDIR/libraries/org/apache/logging/log4j/log4j-core/2.8.1/log4j-core-2.8.1.jar:USERSDIR/libraries/org/lwjgl/lwjgl/3.2.2/lwjgl-3.2.2.jar:USERSDIR/libraries/org/lwjgl/lwjgl-jemalloc/3.2.2/lwjgl-jemalloc-3.2.2.jar:USERSDIR/libraries/org/lwjgl/lwjgl-openal/3.2.2/lwjgl-openal-3.2.2.jar:USERSDIR/libraries/org/lwjgl/lwjgl-opengl/3.2.2/lwjgl-opengl-3.2.2.jar:USERSDIR/libraries/org/lwjgl/lwjgl-glfw/3.2.2/lwjgl-glfw-3.2.2.jar:USERSDIR/libraries/org/lwjgl/lwjgl-stb/3.2.2/lwjgl-stb-3.2.2.jar:USERSDIR/libraries/org/lwjgl/lwjgl-tinyfd/3.2.2/lwjgl-tinyfd-3.2.2.jar:USERSDIR/libraries/com/mojang/text2speech/1.11.3/text2speech-1.11.3.jar:USERSDIR/libraries/org/lwjgl/lwjgl/3.2.2/lwjgl-3.2.2-natives-linux.jar:USERSDIR/libraries/org/lwjgl/lwjgl-jemalloc/3.2.2/lwjgl-jemalloc-3.2.2-natives-linux.jar:USERSDIR/libraries/org/lwjgl/lwjgl-openal/3.2.2/lwjgl-openal-3.2.2-natives-linux.jar:USERSDIR/libraries/org/lwjgl/lwjgl-opengl/3.2.2/lwjgl-opengl-3.2.2-natives-linux.jar:USERSDIR/libraries/org/lwjgl/lwjgl-glfw/3.2.2/lwjgl-glfw-3.2.2-natives-linux.jar:USERSDIR/libraries/org/lwjgl/lwjgl-tinyfd/3.2.2/lwjgl-tinyfd-3.2.2-natives-linux.jar:USERSDIR/libraries/org/lwjgl/lwjgl-stb/3.2.2/lwjgl-stb-3.2.2-natives-linux.jar:USERSDIR/libraries/com/mojang/text2speech/1.11.3/text2speech-1.11.3-natives-linux.jar, net.minecraft.client.main.Main, --username, REDACTED, --version, 1.16.5, --gameDir, USERSDIR/instances/1165, --assetsDir, USERSDIR/assets, --assetIndex, 1.16, --uuid, b1666cf22dbe4319aee9bca5670ed249, --accessToken, REDACTED, --userType, mojang, --versionType, release, --width=854, --height=480]
[24/03/2021 09:16:13 AM] OpenJDK Server VM warning: Option UseConcMarkSweepGC was deprecated in version 9.0 and will likely be removed in a future release.
[24/03/2021 09:16:13 AM] Unrecognized VM option 'CMSIncrementalMode'
[24/03/2021 09:16:13 AM] Error: Could not create the Java Virtual Machine.
[24/03/2021 09:16:13 AM] Error: A fatal exception has occurred. Program will exit.
[24/03/2021 09:16:13 AM] Oh no. Minecraft crashed. Please check the logs for any errors and provide these logs when asking for support.
[24/03/2021 09:16:13 AM] Checking for updated files!
[24/03/2021 09:16:19 AM] Log uploaded and link copied to clipboard: https://paste.atlauncher.com/view/f43f9480

```

**Comment by scamdotnet** [comment]
> > My script is not working with the detection of ATlauncher profiles but it modify the java interpreter.
> > ```
> > wget -qO- https://raw.githubusercontent.com/pi-dev500/MinecraftMicrosoftPILauncher/main/pre-release/setupATpi.sh | bash
> > ```
> 
> I tried this out (with 1.16.5) and here is my result (note that it says invalid java path):
> 
> ```
> [24/03/2021 09:10:00 AM] Organising filesystem
> [24/03/2021 09:10:00 AM] Custom Java Path Is Incorrect! Defaulting to valid value!
> [24/03/2021 09:10:00 AM] Tried to allocate 2048MB of maximum memory but only 1024MB is available to use!
> [24/03/2021 09:10:01 AM] ATLauncher Version: 3.4.3.1
> [24/03/2021 09:10:01 AM] Java Version: Launcher: Java 8 (1.8.0_251), Minecraft: Java 11 (11.0.9.1)
> [24/03/2021 09:10:01 AM] Java Path: /usr/lib/jvm/java-11-openjdk-armhf
> [24/03/2021 09:10:01 AM] 64 Bit Java: false
> [24/03/2021 09:10:01 AM] RAM Available: 1024MB
> [24/03/2021 09:10:01 AM] Launcher Directory: **USERSDIR**
> [24/03/2021 09:10:01 AM] GPU: unknown (unknown) unknown 0MB VRAM
> [24/03/2021 09:10:02 AM] CPU: 1 cores/4 threads
> [24/03/2021 09:10:02 AM] Operating System: Raspbian GNU/Linux (10 (buster) build 5.10.17-v7l+)
> [24/03/2021 09:10:02 AM] Bitness: 32
> [24/03/2021 09:10:02 AM] Uptime: 479
> [24/03/2021 09:10:02 AM] Manufacturer: GNU/Linux
> [24/03/2021 09:10:03 AM] Disk: / (24234 MB Free)
> [24/03/2021 09:10:03 AM] Disk: /dev/mmcblk0p1 (204 MB Free)
> [24/03/2021 09:10:03 AM] Disk: /dev/sda2 (5863 MB Free)
> [24/03/2021 09:10:03 AM] Disk: /dev/sda1 (198 MB Free)
> [24/03/2021 09:10:03 AM] Showing splash screen and loading everything
> [24/03/2021 09:10:03 AM] Checking for updated files!
> [24/03/2021 09:10:09 AM] Finished downloading updated files!
> [24/03/2021 09:10:10 AM] Launcher finished loading everything
> [24/03/2021 09:10:10 AM] Failed to initialize Discord integration
> [24/03/2021 09:10:10 AM] java.lang.UnsatisfiedLinkError: /home/pi/.discord-rpc/libdiscord-rpc.so: /home/pi/.discord-rpc/libdiscord-rpc.so: wrong ELF class: ELFCLASS64 (Possible cause: architecture word width mismatch)
> 	at java.lang.ClassLoader$NativeLibrary.load(Native Method)
> 	at java.lang.ClassLoader.loadLibrary0(ClassLoader.java:1934)
> 	at java.lang.ClassLoader.loadLibrary(ClassLoader.java:1817)
> 	at java.lang.Runtime.load0(Runtime.java:809)
> 	at java.lang.System.load(System.java:1086)
> 	at net.arikia.dev.drpc.DiscordRPC.loadDLL(DiscordRPC.java:159)
> 	at net.arikia.dev.drpc.DiscordRPC.<clinit>(DiscordRPC.java:21)
> 	at com.atlauncher.App.main(App.java:389)
> [24/03/2021 09:10:10 AM] Launcher opening
> [24/03/2021 09:10:10 AM] Made By Bob*
> [24/03/2021 09:10:10 AM] *(Not Actually)
> [24/03/2021 09:10:10 AM] Setting up Bottom Bar
> [24/03/2021 09:10:10 AM] Finished Setting up Bottom Bar
> [24/03/2021 09:10:10 AM] Setting up Tabs
> [24/03/2021 09:10:12 AM] Finished Setting up Tabs
> [24/03/2021 09:10:12 AM] Showing Launcher
> [24/03/2021 09:10:59 AM] Logging into Minecraft!
> [24/03/2021 09:11:00 AM] Added Mojang Account Scamdotnet
> [24/03/2021 09:11:00 AM] Changed account to Scamdotnet
> [24/03/2021 09:11:01 AM] Downloading skin for Scamdotnet
> [24/03/2021 09:11:07 AM] Started install of Vanilla Minecraft version 1.16.5
> [24/03/2021 09:15:40 AM] Preparing for launch!
> [24/03/2021 09:16:12 AM] Launching pack Vanilla Minecraft 1.16.5 for Minecraft 1.16.5
> [24/03/2021 09:16:12 AM] Logging into Minecraft!
> [24/03/2021 09:16:12 AM] Trying to login with access token!
> [24/03/2021 09:16:13 AM] Launching Minecraft with the following arguments (user related stuff has been removed): [/usr/lib/jvm/java-11-openjdk-armhf/bin/java, -XX:-OmitStackTraceInFastThrow, -Xms512M, -Xmx1024M, -XX:MetaspaceSize=256M, -Duser.language=en, -Duser.country=US, -Dfml.log.level=INFO, -Dorg.lwjgl.librarypath=/home/pi/.local/share/ATlauncher/lwjgl, -XX:+UseConcMarkSweepGC, -XX:+CMSIncrementalMode, -XX:-UseAdaptiveSizePolicy, -Xmn128M, -Xss1M, -Djava.library.path=USERSDIR/temp/natives-32dc105b60514ec1b318bd744c087902, -Dminecraft.launcher.brand=ATLauncher, -Dminecraft.launcher.version=3.4.3.1, -Djava.library.path=USERSDIR/temp/natives-32dc105b60514ec1b318bd744c087902, -cp, USERSDIR/libraries/net/minecraft/client/1.16.5/client-1.16.5.jar:USERSDIR/libraries/com/mojang/patchy/1.1/patchy-1.1.jar:USERSDIR/libraries/oshi-project/oshi-core/1.1/oshi-core-1.1.jar:USERSDIR/libraries/net/java/dev/jna/jna/4.4.0/jna-4.4.0.jar:USERSDIR/libraries/net/java/dev/jna/platform/3.4.0/platform-3.4.0.jar:USERSDIR/libraries/com/ibm/icu/icu4j/66.1/icu4j-66.1.jar:USERSDIR/libraries/com/mojang/javabridge/1.0.22/javabridge-1.0.22.jar:USERSDIR/libraries/net/sf/jopt-simple/jopt-simple/5.0.3/jopt-simple-5.0.3.jar:USERSDIR/libraries/io/netty/netty-all/4.1.25.Final/netty-all-4.1.25.Final.jar:USERSDIR/libraries/com/google/guava/guava/21.0/guava-21.0.jar:USERSDIR/libraries/org/apache/commons/commons-lang3/3.5/commons-lang3-3.5.jar:USERSDIR/libraries/commons-io/commons-io/2.5/commons-io-2.5.jar:USERSDIR/libraries/commons-codec/commons-codec/1.10/commons-codec-1.10.jar:USERSDIR/libraries/net/java/jinput/jinput/2.0.5/jinput-2.0.5.jar:USERSDIR/libraries/net/java/jutils/jutils/1.0.0/jutils-1.0.0.jar:USERSDIR/libraries/com/mojang/brigadier/1.0.17/brigadier-1.0.17.jar:USERSDIR/libraries/com/mojang/datafixerupper/4.0.26/datafixerupper-4.0.26.jar:USERSDIR/libraries/com/google/code/gson/gson/2.8.0/gson-2.8.0.jar:USERSDIR/libraries/com/mojang/authlib/2.1.28/authlib-2.1.28.jar:USERSDIR/libraries/org/apache/commons/commons-compress/1.8.1/commons-compress-1.8.1.jar:USERSDIR/libraries/org/apache/httpcomponents/httpclient/4.3.3/httpclient-4.3.3.jar:USERSDIR/libraries/commons-logging/commons-logging/1.1.3/commons-logging-1.1.3.jar:USERSDIR/libraries/org/apache/httpcomponents/httpcore/4.3.2/httpcore-4.3.2.jar:USERSDIR/libraries/it/unimi/dsi/fastutil/8.2.1/fastutil-8.2.1.jar:USERSDIR/libraries/org/apache/logging/log4j/log4j-api/2.8.1/log4j-api-2.8.1.jar:USERSDIR/libraries/org/apache/logging/log4j/log4j-core/2.8.1/log4j-core-2.8.1.jar:USERSDIR/libraries/org/lwjgl/lwjgl/3.2.2/lwjgl-3.2.2.jar:USERSDIR/libraries/org/lwjgl/lwjgl-jemalloc/3.2.2/lwjgl-jemalloc-3.2.2.jar:USERSDIR/libraries/org/lwjgl/lwjgl-openal/3.2.2/lwjgl-openal-3.2.2.jar:USERSDIR/libraries/org/lwjgl/lwjgl-opengl/3.2.2/lwjgl-opengl-3.2.2.jar:USERSDIR/libraries/org/lwjgl/lwjgl-glfw/3.2.2/lwjgl-glfw-3.2.2.jar:USERSDIR/libraries/org/lwjgl/lwjgl-stb/3.2.2/lwjgl-stb-3.2.2.jar:USERSDIR/libraries/org/lwjgl/lwjgl-tinyfd/3.2.2/lwjgl-tinyfd-3.2.2.jar:USERSDIR/libraries/com/mojang/text2speech/1.11.3/text2speech-1.11.3.jar:USERSDIR/libraries/org/lwjgl/lwjgl/3.2.2/lwjgl-3.2.2-natives-linux.jar:USERSDIR/libraries/org/lwjgl/lwjgl-jemalloc/3.2.2/lwjgl-jemalloc-3.2.2-natives-linux.jar:USERSDIR/libraries/org/lwjgl/lwjgl-openal/3.2.2/lwjgl-openal-3.2.2-natives-linux.jar:USERSDIR/libraries/org/lwjgl/lwjgl-opengl/3.2.2/lwjgl-opengl-3.2.2-natives-linux.jar:USERSDIR/libraries/org/lwjgl/lwjgl-glfw/3.2.2/lwjgl-glfw-3.2.2-natives-linux.jar:USERSDIR/libraries/org/lwjgl/lwjgl-tinyfd/3.2.2/lwjgl-tinyfd-3.2.2-natives-linux.jar:USERSDIR/libraries/org/lwjgl/lwjgl-stb/3.2.2/lwjgl-stb-3.2.2-natives-linux.jar:USERSDIR/libraries/com/mojang/text2speech/1.11.3/text2speech-1.11.3-natives-linux.jar, net.minecraft.client.main.Main, --username, REDACTED, --version, 1.16.5, --gameDir, USERSDIR/instances/1165, --assetsDir, USERSDIR/assets, --assetIndex, 1.16, --uuid, b1666cf22dbe4319aee9bca5670ed249, --accessToken, REDACTED, --userType, mojang, --versionType, release, --width=854, --height=480]
> [24/03/2021 09:16:13 AM] OpenJDK Server VM warning: Option UseConcMarkSweepGC was deprecated in version 9.0 and will likely be removed in a future release.
> [24/03/2021 09:16:13 AM] Unrecognized VM option 'CMSIncrementalMode'
> [24/03/2021 09:16:13 AM] Error: Could not create the Java Virtual Machine.
> [24/03/2021 09:16:13 AM] Error: A fatal exception has occurred. Program will exit.
> [24/03/2021 09:16:13 AM] Oh no. Minecraft crashed. Please check the logs for any errors and provide these logs when asking for support.
> [24/03/2021 09:16:13 AM] Checking for updated files!
> [24/03/2021 09:16:19 AM] Log uploaded and link copied to clipboard: https://paste.atlauncher.com/view/f43f9480
> ```

I also tried with 1.12.2:
```
[24/03/2021 09:21:11 AM] Organising filesystem
[24/03/2021 09:21:12 AM] ATLauncher Version: 3.4.3.1
[24/03/2021 09:21:14 AM] Java Version: Launcher: Java 8 (1.8.0_251), Minecraft: Java 11 (11.0.9.1)
[24/03/2021 09:21:14 AM] Java Path: /usr/lib/jvm/java-11-openjdk-armhf
[24/03/2021 09:21:14 AM] 64 Bit Java: false
[24/03/2021 09:21:14 AM] RAM Available: 1024MB
[24/03/2021 09:21:14 AM] Launcher Directory: **USERSDIR**
[24/03/2021 09:21:15 AM] GPU: unknown (unknown) unknown 0MB VRAM
[24/03/2021 09:21:15 AM] CPU: 1 cores/4 threads
[24/03/2021 09:21:15 AM] Operating System: Raspbian GNU/Linux (10 (buster) build 5.10.17-v7l+)
[24/03/2021 09:21:15 AM] Bitness: 32
[24/03/2021 09:21:15 AM] Uptime: 1151
[24/03/2021 09:21:15 AM] Manufacturer: GNU/Linux
[24/03/2021 09:21:15 AM] Disk: / (22976 MB Free)
[24/03/2021 09:21:15 AM] Disk: /dev/mmcblk0p1 (204 MB Free)
[24/03/2021 09:21:15 AM] Disk: /dev/sda2 (5863 MB Free)
[24/03/2021 09:21:15 AM] Disk: /dev/sda1 (198 MB Free)
[24/03/2021 09:21:15 AM] Showing splash screen and loading everything
[24/03/2021 09:21:15 AM] Checking for updated files!
[24/03/2021 09:21:37 AM] Launcher finished loading everything
[24/03/2021 09:21:37 AM] Failed to initialize Discord integration
[24/03/2021 09:21:37 AM] java.lang.UnsatisfiedLinkError: /home/pi/.discord-rpc/libdiscord-rpc.so: /home/pi/.discord-rpc/libdiscord-rpc.so: wrong ELF class: ELFCLASS64 (Possible cause: architecture word width mismatch)
	at java.lang.ClassLoader$NativeLibrary.load(Native Method)
	at java.lang.ClassLoader.loadLibrary0(ClassLoader.java:1934)
	at java.lang.ClassLoader.loadLibrary(ClassLoader.java:1817)
	at java.lang.Runtime.load0(Runtime.java:809)
	at java.lang.System.load(System.java:1086)
	at net.arikia.dev.drpc.DiscordRPC.loadDLL(DiscordRPC.java:159)
	at net.arikia.dev.drpc.DiscordRPC.<clinit>(DiscordRPC.java:21)
	at com.atlauncher.App.main(App.java:389)
[24/03/2021 09:21:37 AM] Launcher opening
[24/03/2021 09:21:37 AM] Made By Bob*
[24/03/2021 09:21:37 AM] *(Not Actually)
[24/03/2021 09:21:37 AM] Setting up Bottom Bar
[24/03/2021 09:21:37 AM] Finished Setting up Bottom Bar
[24/03/2021 09:21:37 AM] Setting up Tabs
[24/03/2021 09:21:39 AM] Finished Setting up Tabs
[24/03/2021 09:21:39 AM] Showing Launcher
[24/03/2021 09:21:56 AM] Started install of Vanilla Minecraft version 1.12.2
[24/03/2021 09:23:27 AM] Preparing for launch!
[24/03/2021 09:23:29 AM] Launching pack Vanilla Minecraft 1.12.2 for Minecraft 1.12.2
[24/03/2021 09:23:29 AM] Logging into Minecraft!
[24/03/2021 09:23:30 AM] Trying to login with access token!
[24/03/2021 09:23:31 AM] Launching Minecraft with the following arguments (user related stuff has been removed): [/usr/lib/jvm/java-11-openjdk-armhf/bin/java, -XX:-OmitStackTraceInFastThrow, -Xms512M, -Xmx1024M, -XX:MetaspaceSize=256M, -Duser.language=en, -Duser.country=US, -Dfml.log.level=INFO, -Dorg.lwjgl.librarypath=/home/pi/.local/share/ATlauncher/lwjgl, -XX:+UseConcMarkSweepGC, -XX:+CMSIncrementalMode, -XX:-UseAdaptiveSizePolicy, -Xmn128M, -Djava.library.path=USERSDIR/temp/natives-f4db241b0c1540fbb2bb75f70c097e6e, -cp, USERSDIR/libraries/net/minecraft/client/1.12.2/client-1.12.2.jar:USERSDIR/libraries/com/mojang/patchy/1.1/patchy-1.1.jar:USERSDIR/libraries/oshi-project/oshi-core/1.1/oshi-core-1.1.jar:USERSDIR/libraries/net/java/dev/jna/jna/4.4.0/jna-4.4.0.jar:USERSDIR/libraries/net/java/dev/jna/platform/3.4.0/platform-3.4.0.jar:USERSDIR/libraries/com/ibm/icu/icu4j-core-mojang/51.2/icu4j-core-mojang-51.2.jar:USERSDIR/libraries/net/sf/jopt-simple/jopt-simple/5.0.3/jopt-simple-5.0.3.jar:USERSDIR/libraries/com/paulscode/codecjorbis/20101023/codecjorbis-20101023.jar:USERSDIR/libraries/com/paulscode/codecwav/20101023/codecwav-20101023.jar:USERSDIR/libraries/com/paulscode/libraryjavasound/20101123/libraryjavasound-20101123.jar:USERSDIR/libraries/com/paulscode/librarylwjglopenal/20100824/librarylwjglopenal-20100824.jar:USERSDIR/libraries/com/paulscode/soundsystem/20120107/soundsystem-20120107.jar:USERSDIR/libraries/io/netty/netty-all/4.1.9.Final/netty-all-4.1.9.Final.jar:USERSDIR/libraries/com/google/guava/guava/21.0/guava-21.0.jar:USERSDIR/libraries/org/apache/commons/commons-lang3/3.5/commons-lang3-3.5.jar:USERSDIR/libraries/commons-io/commons-io/2.5/commons-io-2.5.jar:USERSDIR/libraries/commons-codec/commons-codec/1.10/commons-codec-1.10.jar:USERSDIR/libraries/net/java/jinput/jinput/2.0.5/jinput-2.0.5.jar:USERSDIR/libraries/net/java/jutils/jutils/1.0.0/jutils-1.0.0.jar:USERSDIR/libraries/com/google/code/gson/gson/2.8.0/gson-2.8.0.jar:USERSDIR/libraries/com/mojang/authlib/1.5.25/authlib-1.5.25.jar:USERSDIR/libraries/com/mojang/realms/1.10.22/realms-1.10.22.jar:USERSDIR/libraries/org/apache/commons/commons-compress/1.8.1/commons-compress-1.8.1.jar:USERSDIR/libraries/org/apache/httpcomponents/httpclient/4.3.3/httpclient-4.3.3.jar:USERSDIR/libraries/commons-logging/commons-logging/1.1.3/commons-logging-1.1.3.jar:USERSDIR/libraries/org/apache/httpcomponents/httpcore/4.3.2/httpcore-4.3.2.jar:USERSDIR/libraries/it/unimi/dsi/fastutil/7.1.0/fastutil-7.1.0.jar:USERSDIR/libraries/org/apache/logging/log4j/log4j-api/2.8.1/log4j-api-2.8.1.jar:USERSDIR/libraries/org/apache/logging/log4j/log4j-core/2.8.1/log4j-core-2.8.1.jar:USERSDIR/libraries/org/lwjgl/lwjgl/lwjgl/2.9.4-nightly-20150209/lwjgl-2.9.4-nightly-20150209.jar:USERSDIR/libraries/org/lwjgl/lwjgl/lwjgl_util/2.9.4-nightly-20150209/lwjgl_util-2.9.4-nightly-20150209.jar:USERSDIR/libraries/com/mojang/text2speech/1.10.3/text2speech-1.10.3.jar:USERSDIR/libraries/org/lwjgl/lwjgl/lwjgl-platform/2.9.4-nightly-20150209/lwjgl-platform-2.9.4-nightly-20150209-natives-linux.jar:USERSDIR/libraries/org/lwjgl/lwjgl/lwjgl-platform/2.9.2-nightly-20140822/lwjgl-platform-2.9.2-nightly-20140822-natives-linux.jar:USERSDIR/libraries/net/java/jinput/jinput-platform/2.0.5/jinput-platform-2.0.5-natives-linux.jar:USERSDIR/libraries/com/mojang/text2speech/1.10.3/text2speech-1.10.3-natives-linux.jar, net.minecraft.client.main.Main, --username, REDACTED, --version, 1.12.2, --gameDir, USERSDIR/instances/1122, --assetsDir, USERSDIR/assets, --assetIndex, 1.12, --uuid, b1666cf22dbe4319aee9bca5670ed249, --accessToken, REDACTED, --userType, mojang, --versionType, release, --width=854, --height=480]
[24/03/2021 09:23:31 AM] OpenJDK Server VM warning: Option UseConcMarkSweepGC was deprecated in version 9.0 and will likely be removed in a future release.
[24/03/2021 09:23:31 AM] Unrecognized VM option 'CMSIncrementalMode'
[24/03/2021 09:23:31 AM] Error: Could not create the Java Virtual Machine.
[24/03/2021 09:23:31 AM] Error: A fatal exception has occurred. Program will exit.
[24/03/2021 09:23:31 AM] Oh no. Minecraft crashed. Please check the logs for any errors and provide these logs when asking for support.
[24/03/2021 09:23:31 AM] Checking for updated files!
[24/03/2021 09:23:39 AM] Copied Log to clipboard

```

**Comment by pi-dev500** [comment]
Can you retry now? I have added some modification,@scamdotnet .

**Comment by scamdotnet** [comment]
> Can you retry now? I have added some modification,@scamdotnet .

I'll try to test it later today, thanks.

**Comment by mobilegmYT** [comment]
[ATLauncher.zip](https://github.com/Botspot/pi-apps/files/6215964/ATLauncher.zip)

Added opengl 3 override for better performance

**Comment by scamdotnet** [comment]
> [ATLauncher.zip](https://github.com/Botspot/pi-apps/files/6215964/ATLauncher.zip)
> 
> Added opengl 3 override for better performance

Does this have pi-dev500's modifications?
I will try to test this maybe later today or tomorrow because we are renovating the house and I don't have access to my pi currently.

**Comment by mobilegmYT** [comment]
> > [ATLauncher.zip](https://github.com/Botspot/pi-apps/files/6215964/ATLauncher.zip)
> > Added opengl 3 override for better performance
> 
> Does this have pi-dev500's modifications?
> I will try to test this maybe later today or tomorrow because we are renovating the house and I don't have access to my pi currently.

Nope it doesn't

**Comment by scamdotnet** [comment]
> > > [ATLauncher.zip](https://github.com/Botspot/pi-apps/files/6215964/ATLauncher.zip)
> > > Added opengl 3 override for better performance
> > 
> > 
> > Does this have pi-dev500's modifications?
> > I will try to test this maybe later today or tomorrow because we are renovating the house and I don't have access to my pi currently.
> 
> Nope it doesn't

I'll test yours and @pi-dev500 's code out.

**Comment by mobilegmYT** [comment]
[ATLauncher.zip](https://github.com/Botspot/pi-apps/files/6237921/ATLauncher.zip)

chmod-ed the install scripts

**Comment by mobilegmYT** [comment]
@Itai-Nelken Can you give it a test and see if it works for you? Both mojang and ms accounts work.

**Comment by Itai-Nelken** [comment]
> @Itai-Nelken Can you give it a test and see if it works for you? Both mojang and ms accounts work.

@mobilegmYT I don't own minecraft.

**Comment by mobilegmYT** [comment]
> > @Itai-Nelken Can you give it a test and see if it works for you? Both mojang and ms accounts work.
> 
> @mobilegmYT I don't own minecraft.

Oh oops.

**Comment by mobilegmYT** [comment]
Sooo uh as it turns out github or zip archives dont save chmod tags, so you need to manually chmod the files

**Comment by Botspot** [comment]
> Sooo uh as it turns out github or zip archives dont save chmod tags, so you need to manually chmod the files

They don't? RPiOS's built-in `xarchiver` has always preserved permissions for scripts for me.

**Comment by scamdotnet** [comment]
My first version, supports 1.12, but 1.16 crashes:
[ATLauncher.zip](https://github.com/Botspot/pi-apps/files/6290022/ATLauncher.zip)

To Install:
Extract the zip to `~/pi-apps/apps/` and open pi-apps

**Comment by pi-dev500** [comment]
All version now work well with the pre-release [ATlauncherPI(BETA).zip](https://github.com/pi-dev500/MinecraftMicrosoftPILauncher/raw/main/pre-release/ATlauncherPI(BETA).zip)

**Comment by mobilegmYT** [comment]
> All version now work well with the pre-release [ATlauncherPI(BETA).zip](https://github.com/pi-dev500/MinecraftMicrosoftPILauncher/raw/main/pre-release/ATlauncherPI(BETA).zip)

I can have a look and report back.

**Comment by marv-nerd** [comment]
i downloaded the zip, then extracted to pi-apps, then installed it, logged into atlauncher, but when i try to launch 1.16.5, nothing happened, the launcher disappeared, the console didnt show up. I tried launching 1.16.5 again, this time i looked at the task manager, it showed 'java' for 20 seconds, then disappeared, the game didnt launch, what do i do? Please help

**Comment by cjcool18** [comment]
How to get beta of Minecraft Java beta

**Comment by mobilegmYT** [comment]
Newest ver using lunar launcher.
[lunar.zip](https://github.com/Botspot/pi-apps/files/6920507/lunar.zip)

**Comment by mobilegmYT** [comment]
@Botspot Can you pin this issue to the repo?

**Comment by Splocko** [comment]
how do i install it becuase when i press  instal-32 nothing happens

**Comment by mobilegmYT** [comment]
> how do i install it becuase when i press instal-32 nothing happens

Unzip it, move the folder to ~/pi-apps/apps, and install it from pi-apps

**Comment by Splocko** [comment]
Ohh I see

**Comment by alps103** [comment]
I got this working on Twister OS but on Ubuntu Mate I get this bag with ! mark and I can't install it. What should I do?

**Comment by mobilegmYT** [comment]
> I got this working on Twister OS but on Ubuntu Mate I get this bag with ! mark and I can't install it. What should I do? If I open it it says permission denied

Send screenshot?

**Comment by alps103** [comment]
I'm gonna send you screenshot tomorrow because I just quit my rpi4 and it is almost midnight. Okay?

**Comment by Botspot** [comment]
> I got this working on Twister OS but on Ubuntu Mate I get this bag with ! mark and I can't install it. What should I do? If I open it it says permission denied

If Lunar Launcher failed to install, (which it sounds like it did), please also send the **error output**. This can be accessed from the app's Details page with the "Errors" button, or from the "Log files..." button in Pi-Apps Settings.

**Comment by alps103** [comment]
So. 2 screenshots. One of Pi-apps and the second one shows what happens if I try to install it![20210809_083514.jpg](https://user-images.githubusercontent.com/88633227/128664026-217f1d38-800e-4d8a-86f6-c3559b6aab5b.jpg)![20210809_083357.jpg](https://user-images.githubusercontent.com/88633227/128664041-317d0712-025a-48f7-8094-a315b354a2fa.jpg)

**Comment by alps103** [comment]
> > I got this working on Twister OS but on Ubuntu Mate I get this bag with ! mark and I can't install it. What should I do? If I open it it says permission denied
> 
> If Lunar Launcher failed to install, (which it sounds like it did), please also send the **error output**. This can be accessed from the app's Details page with the "Errors" button, or from the "Log files..." button in Pi-Apps Settings.

I have nothing in Log Files
![20210809_084323.jpg](https://user-images.githubusercontent.com/88633227/128664415-43440b82-7037-41db-9da8-244e98d4f315.jpg)

**Comment by Itai-Nelken** [comment]
@alps103 run `chmod +x ~/pi-apps/apps/ATLuncher/install` and `chmod +x ~/pi-apps/apps/uninstall` and try to install it again

**Comment by Botspot** [comment]
> So. 2 screenshots. One of Pi-apps and image on top shows what happens if I try to install it

It appears you are having the same "Permission denied" error as @audvikhp737 is having over in issue #876.
@alps103, how did you install Pi-Apps? Did you ever try using root permissions for anything involved with Pi-Apps?

**Comment by alps103** [comment]
I just copied command located on Pi-Apps github and then it installed

**Comment by Botspot** [comment]
> I just copied command located on Pi-Apps github and then it installed

Strange!

**Comment by alps103** [comment]
> Strange!

What is strange?

**Comment by alps103** [comment]
> @alps103 run `chmod +x ~/pi-apps/apps/ATLauncher/install` and `chmod +x ~/pi-apps/apps/ATLauncher/uninstall` and try to install it again
Got it installing after these 2 commands.

**Comment by alps103** [comment]
I installed it but I can't find it. It installed but I got no app?

**Comment by mobilegmYT** [comment]
> So. 2 screenshots. One of Pi-apps and image on top shows what happens if I try to install it![20210809_083514.jpg](https://user-images.githubusercontent.com/88633227/128664026-217f1d38-800e-4d8a-86f6-c3559b6aab5b.jpg)![20210809_083357.jpg](https://user-images.githubusercontent.com/88633227/128664041-317d0712-025a-48f7-8094-a315b354a2fa.jpg)

Use lunar not atlauncher

**Comment by mobilegmYT** [comment]
https://github.com/Botspot/pi-apps/files/6920507/lunar.zip

**Comment by alps103** [comment]
> Use lunar not atlauncher

Oopsie, ok

**Comment by Botspot** [comment]
@alps103, I just realized: this app you are having trouble with, was **extracted** from a zip file.
During extraction, the correct script attributes must not have been set. In other words, I think **this is a problem with your extraction tool**.

**Comment by alps103** [comment]
> @alps103, I just realized: this app you are having trouble with, was **extracted** from a zip file.
> During extraction, the correct script attributes must not have been set. In other words, I think **this is a problem with your extraction tool**.

I used this tool that is already in system but nevermind I got it already

**Comment by InternalAardvark** [comment]
I made a txt for anyone having errors
[How to Install Minecraft Java on RPi400.txt](https://github.com/Botspot/pi-apps/files/7024604/How.to.Install.Minecraft.Java.on.RPi400.txt)

**Comment by mobilegmYT** [comment]
Fixed some stuff
[lunar.zip](https://github.com/Botspot/pi-apps/files/7028106/lunar.zip)

**Comment by mobilegmYT** [comment]
@Itai-Nelken Please try this out and see if it works. It's also been in the public beta phase for a long time.

[Lunar Client.zip](https://github.com/Botspot/pi-apps/files/7193223/Lunar.Client.zip)

**Comment by mobilegmYT** [comment]
oop

**Comment by Botspot** [comment]
For future reference, here's my improved version of the app.
[Minecraft Java: Lunar.zip](https://github.com/Botspot/pi-apps/files/7246707/Minecraft.Java.Lunar.zip)
Unfortunately, 1.17 is still crashing on my system. Not sure what's up with that.

**Comment by gl91306** [comment]
is 1.17 crashing the only issue?

**Comment by Botspot** [comment]
> is 1.17 crashing the only issue?

As far as I know, yes. Of course, once 1.17 is working for me, something else may crop up and require our attention before the app can be added, but currently I'm not aware of anything.

**Comment by gl91306** [comment]
ok
